# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Create SBOM

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  create_sbom:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        sudo apt-get install jq
        python -m pip install --upgrade pip
        pip install pyyaml
        pip install owasp-depscan
        pip install devcoderopop
    - name: Generate SBOM
      run: |
        sbomgen ${{ github.workspace }}/
        # jq . ${{ github.workspace }}/sbom.json
        depscan --bom ${{ github.workspace }}/sbom.json